{
 "title": "Photo backlog status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "photo_backlog_processing_time_seconds"
    }
   },
   { "name": "top_folder_count", "label": "Top N count", "query": "15" }
  ]
 },
 "panels": [
  {
   "title": "Photo backlog count | $host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "photo_backlog_counts{instance=~\"$host\", kind=\"photos\"}",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "photo_backlog_counts{instance=~\"$host\", kind=\"folders\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Photo processing  volume | $host",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(photo_backlog_counts{instance=~\"$host\", kind=\"photos\"}[1h])*3600",
     "legendFormat": "{{kind}}"
    },
    {
     "expr": "rate(photo_backlog_counts{instance=~\"$host\", kind=\"folders\"}[1h])*3600",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Folder sizes | $host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk($top_folder_count, photo_backlog_folder_sizes{instance=\"$host\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Per-folder picture-seconds cumulative backlog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "topk($top_folder_count, photo_backlog_folder_ages{instance=~\"$host\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "File age distribution | $host",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "photo_backlog_ages_bucket{instance=\"$host\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backlog errors",
   "type": "timeseries",
   "description": "Errors while scanning the backlog split by type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "photo_backlog_errors{instance=\"$host\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Processing time | $host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "photo_backlog_processing_time_seconds{instance=\"$host\"}",
     "legendFormat": "Processing time"
    }
   ]
  }
 ]
}